on:
 push:
   branches: main
 workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Install R
      - uses: r-lib/actions/setup-r@v2

      # Install required R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Publish to GitHub Pages
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
